# Generated by Django 5.2.1 on 2025-06-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
